name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (needed for some actions, like 'actions/github-pages-deploy-action')
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can use any version you prefer

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages   # This is the branch where your GitHub Pages site will live
        folder: .           # Folder to deploy (use '.' for the root directory)
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided GitHub token

